"""Process-local correlation between a native draft question and its reply send."""

from contextvars import ContextVar
from dataclasses import dataclass


_capture = ContextVar("native_cron_clarifications", default=None)


@dataclass(frozen=True)
class DraftQuestion:
    kind: str
    sender: str
    recipient: str
    token: object


def capture_call(producer, *args, **kwargs):
    """Collect only questions generated by this native call, never stored prose."""
    questions = []
    reset = _capture.set(questions)
    try:
        return producer(*args, **kwargs), questions
    finally:
        _capture.reset(reset)


def generated(kind, sender, recipient):
    """Opaque identity is ephemeral and is never an authorization credential."""
    token = object()
    questions = _capture.get()
    if questions is not None:
        questions.append(DraftQuestion(kind, sender, recipient, token))
    return token


def discard_unseen(questions):
    from . import cron_creation, research_cron
    for question in questions:
        module = cron_creation if question.kind == "ordinary" else research_cron
        module.clear_question(question.sender, question.recipient, question.token)
